### PR TITLE
Restructure repo: python/tensorflow_cloud/core to tensorflow_cloud/py…

### PR DESCRIPTION
**Pull request by pavithrasv**
…thon/core.

- All new projects can be added under tensorflow_cloud.
- Cleaned up paths in all the files and updated package structure accordingly.

### CODE REVIEW

**Comment by pavithrasv** [comment]
Fixes #80

**Comment by ucdmkt** [comment]
\cc @SinaChavoshi 

Since `./tensorflow_cloud` is by definition designed for Python package (because `setup.py` is placed at the root level),  the sub-directory `./tensorflow_cloud/python` is redundant.

The original structure had a advantage that the Python source tree for the `tensorflow_cloud` package are isolated  under `pytion/tensorflow_cloud/..` (with the setuptool harness at `python/setup.py`), while keeping ability to have non-Python (C++) build outside of Python source tree and still be able to put dependency on non-Python from the `tensorflow_cloud` Python package.

May we partially revert this PR to isolate Python source tree one level below, so that we have room for non-Python source tree?

**Comment by pavithrasv** [comment]
Thank you Makoto, I'll sync up with you on this tomorrow and make sure we have a setup that works for non-python source tree as well.

**Comment by pavithrasv** [comment]
@ucdmkt can we have
tensorflow_cloud/python/core/...
tensorflow_cloud/cpp/monitoring/...
and in setup.py exclude cpp folder in packaging?

**Comment by pavithrasv** [comment]
Discussed offline and created https://github.com/tensorflow/cloud/pull/91

**Pull request merged**
