### PR TITLE
Remove py 3.5 from docs and testing.

### PR DESCRIPTION
**Pull request by pavithrasv**

### CODE REVIEW

**Comment by ucdmkt** [comment]
Do you need to mark this as a part of release note, since this is backward-incompatible change?

Since this change isn't because of code change in this library per se, another option would have been to cap upperbound of dependency on Keras/TF. Having that said, since Py3.5 EOL is already past, I think either approach is fine.

**Comment by pavithrasv** [comment]
> Do you need to mark this as a part of release note, since this is backward-incompatible change?
> 
> Since this change isn't because of code change in this library per se, another option would have been to cap upperbound of dependency on Keras/TF. Having that said, since Py3.5 EOL is already past, I think either approach is fine.

Added to release notes.

**Review by ucdmkt — APPROVED** [review]
\lgtm

**Comment by SinaChavoshi** [comment]
\lgtm

**Review by SinaChavoshi — APPROVED** [review]

**Pull request merged**
